SET TOKO_DB_USER=root
SET TOKO_DB_PASS=
SET TOKO_DB_DB=toko
SET TOKO_DB_HOST=localhost

SET NODE_NAV_LAPAK=1
SET NODE_NAV_LOGIN=1
SET NODE_NAV_CARI=1
SET NODE_TERKAIT=0
SET NODE_NAMA_TOKO=Warung WA
SET NODE_JML_PER_HAL=25
SET NODE_FOOTER=Warung WA - Warungnya kita kita
SET NODE_FIRE_BASE_CONFIG=1
SET NODE_TOKO_ID=2
SET NODE_MODE_DEV=0
SET NODE_WEB_SITE=http://warungwa.hagarden.xyz

node App
pause